### ISSUE TITLE
Gem

### ISSUE THREAD

**Issue by ghost** [jakewmeyer/Ruby-Scripts#15]
Hello Jake,

Following my comment on reddit, I would like to suggest to you that you may put these scripts also into a gem. That way others can also do "gem install <name>" easily.

**Comment by jakewmeyer** [comment]
Thanks for the feedback

I'll look into it, should be easier than a custom install solution

**Comment by jakewmeyer** [comment]
Scripts are now packaged in a gem.

```ruby
gem install jake-scripts
```
