### ISSUE TITLE
Code style - puts without arguments and using a class perhaps for shared code

### ISSUE THREAD

**Issue by ghost** [jakewmeyer/Ruby-Scripts#16]
Heya Jake,

I think you can safely omit the arguments to puts, in other words,

    puts ''

should be equivalent to:

    puts

If you want to you can also use something such as:

    alias e puts

To make things even shorter. Anyway, it's great that you published code,
several of the code I have not ever thought about, such as encrypt, but
also the weather API showing more information than temperature (I
had a very simple weather script but only for local use in my country
and only the temperature; I never had the idea to include wind etc...)

By the way, I have noticed that you used the same banner for many 
scripts. You can probably write this into a shared code, or into a 
class and re-use that class. This may be a bit extra work since your
code is very simple so not really a need to do so, but if you intend
to add more code into your project there, I think it may be easier for
you to keep things more organized, and classes do help a lot here in
ruby. Feel free to close this issue at any moment in time, I just wanted
to give some feedback!

**Comment by jakewmeyer** [comment]
Awesome feedback.

Had no idea you could use puts without an argument, I'll revise that.

Agreed on the shared code part. Using a modular style would streamline the process greatly, and make similar apps easier in the future. I'm new to ruby, so I'm just scratching the surface of classes and object oriented ideas. 

That'll be my next goal, to revise puts, and look into adding classes for reusability's sake.

Again, really appreciate the feedback
