### ISSUE TITLE
LoadError with all commands

### ISSUE THREAD

**Issue by mattwelke** [jakewmeyer/Ruby-Scripts#17]
When I try to use any of the commands from this gem, I get an error message mentioning a LoadError:

```
[mwelke@mdesk-arch ~]$ weather
/home/mwelke/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rest-client (LoadError)
        from /home/mwelke/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/mwelke/.rvm/gems/ruby-2.4.1/gems/jake-scripts-0.2.0/exe/weather:4:in `<top (required)>'
        from /home/mwelke/.rvm/gems/ruby-2.4.1/bin/weather:23:in `load'
        from /home/mwelke/.rvm/gems/ruby-2.4.1/bin/weather:23:in `<main>'
        from /home/mwelke/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
        from /home/mwelke/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

Setup:

- Antergos with all system updates as of today.
- Intel Core i5 CPU

**Comment by jakewmeyer** [comment]
Looking at it

**Comment by jakewmeyer** [comment]
Fixed. Neglected to add runtime dependancies in the Gem.

Gem install again and it should install the dependent gems alongside.

Let me know how it goes

**Comment by mattwelke** [comment]
Yup, it is working now. Thanks for the quick fix.

I do find it a bit strange though that the weather is hard-coded to use Imperial unit like degrees Fahrenheit and miles. Unfortunately, this command in particular isn't really useful for me.

**Comment by jakewmeyer** [comment]
Excellent. Thanks for opening the issue in the first place.

It's hard coded because its applicable to me, and it's what I find most pertinent. I'd like to make it more ambiguous, to be more flexible for different kinds of people. It's in the pipeline for sure.

**Comment by jakewmeyer** [comment]
I'll add an option for it to be metric vs imperial based on the country of the IP address. Should be better for those outside the US, Canada included 👍

**Comment by jakewmeyer** [comment]
Weather script now has support for metric weather. Basically if the IP isn't in the US, it pulls and formats metric data. Give it a whirl.

**Comment by ghost** [comment]
> I do find it a bit strange though that the weather is hard-coded to use Imperial unit
> like degrees Fahrenheit and miles. Unfortunately, this command in particular isn't
> really useful for me.

I understand that, too. My weather script, for example, can only deal with local data,
that is, in the middle of Europe - which isn't really useful to people living elsewhere. :)

It's often a question of how much time to spend too, depending on how many other
people are using the code. I guess jake already got quite some feedback from different
people by now, things will surely improve over time. :D

In regards to units, conversion should be quite simple in general since it's mostly just
one float that makes a difference (e. g. fahrenheit to celsius, you have that fixed float
for multiplication/division), so adding support for that should be easy.

PS: I didn't know the canadians do NOT use the imperial units, they are thus brighter
than the UK folks who even keep on driving in the wrong direction on the streets! :D

**Comment by jakewmeyer** [comment]
Just want it to be useful to as many people as possible 👍 

The fix was easy to implement, since the api response already has the metric data attached, and if it's anything outside the US, it's basically metric. Ditto on not knowing that Canada uses the metric system.

**Comment by mattwelke** [comment]
> I'll add an option for it to be metric vs imperial based on the country of the IP address. Should be better for those outside the US, Canada included

That's brilliant actually. Reading my comment again, I think I was a bit rude and I apologize for that. This is incredibly useful I think. I have some other wishlist suggestions, but I think I'll make other issues for them. Thanks for the work you've done these scripts!

**Comment by jakewmeyer** [comment]
No worries, good feedback the whole time. 

Pass the suggestions along, and I'll give it my best shot 👍
