### ISSUE TITLE
allow command arguments and machine-readable output

### ISSUE THREAD

**Issue by mattwelke** [jakewmeyer/Ruby-Scripts#18]
I have a suggestion that would help the commands be more useful to those creating scripts. It would also help the commands be used together in interesting ways.

Right now, many of them are interactive. They take an argument but you can't provide it as a command argument, you have to wait until the command runs and then you're prompted. For example, with ```ip_geo```, you're prompted what IP address you want. I noticed the ```stock``` and ```currency``` commands work this way too.

What I think would work better is if the command also allowed you to specify the argument as you run it, to avoid being prompted, for example. I could run ```ip_geo``` like:

```ip_geo 123.234.345.456```

and get its output.

To go along with this, it would be neat if we could use options for the commands to make them only output pieces of data, so that they could be piped into other commands (perhaps even other Ruby-Scripts commands). For example, I could use an option for only outputting the WAN IP from ```ip_list``` and use it this way, with ```ip_geo``` (```-m``` for "machine output" etc):

```ip_list -m wan | xargs ip_geo -m isp```

...and I'd end up with only my ISP name in stdout.

What I envision is a sort of syntax with an option (like my ```-m``` option above) to specify which output values you'd want. Perhaps, with ```ip_list```, the option ```-m wan,lan1``` would print just the WAN address followed by the first LAN address, with a default delimiter (maybe a space). If all the commands were built this way, they could be combined in interesting ways.

**Comment by jakewmeyer** [comment]
Agreed. Once you get used to the scripts, it doesn't make sense to prompt for input after while, and would be better served as an command line argument. 

The specific flags are definitely possible using Optionparser, and would be useful when trying to pipe the output data to other programs.

I'll start off by allowing arguments to be passed to the programs to circumvent the prompts for input.

After that I'll see about adding flags to allow for plain output from the programs for easy piping.

**Comment by jakewmeyer** [comment]
**ip_geo** now has three additional capabilities

```bash
ip_geo 8.8.8.8
```
```bash
ip_geo -m isp
```
```bash
ip_geo -m isp 8.8.8.8
```

Other arguments for the -m flag are: [ ip, city, region, country, zip, isp ]
Right now you can only have one field after the -m , but I'm looking for a solution where you could pass multiple like below.
```bash
ip_geo -m ip city isp 8.8.8.8
```
Enjoy!

**Comment by jakewmeyer** [comment]
After thinking about it, I think it makes more sense to wrap all three of these ip scripts into a single program, with a well designed cli interface with flags, options, and arguments. I think that's more valuable than a smattering of single function scripts. Better to get it all in one place.

**Comment by jakewmeyer** [comment]
This should be fixed by the ```netgeo``` script, as all output should be machine readable by default.
